name: dart_application_1
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_hotreload: ^1.5.0
  shelf_multipart: ^2.0.0
  mime: ^1.0.0


dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
